### ISSUE TITLE
HTTP pealt üle HTTPS'ile

### ISSUE THREAD

**Issue by CardoEggert** [Kaspar94/TVL#70]
Panna võrk HTTP pealt üle HTTPS'ile.

**Comment by CardoEggert** [comment]
Valik on olemas PRODUCTION'i jaoks, serdid peab juurde lisama lihtsalt.

**Comment by jaagupku** [comment]
Https sisselülitamiseks, tuleb vastavas config failis muuta https: true, ning lisada certi ja private key path
![Config](https://i.imgur.com/jtdsGKd.png)
![Config example](https://i.imgur.com/Rh4FcDZ.png)
