### ISSUE TITLE
Äriklientide andmemudel

### ISSUE THREAD

**Issue by CardoEggert** [Kaspar94/TVL#9]
Valmis teha äriklientide andmemudel, mis vastaks kliendi poolt saadetud ärimudelile.

**Comment by jaagupku** [comment]
[Link](https://www.draw.io/?lightbox=1&highlight=0000ff&edit=_blank&layers=1&nav=1&title=Database%20model.html#R7VhtT9swEP41%2BQjKS9OWj22BTWKTkNg09qly4kvq4caZ477Ar985cZKmoS90lMGASsR%2BfPad7%2BznbFveaLr8JEk6%2BSoocMu16dLyzi3XdbrdLn40cl8gvU6nAGLJqBGqgRv2AAa0DTpjFLKGoBKCK5Y2wVAkCYSqgREpxaIpFgne1JqSGFrATUh4G%2F3BqJoUaN%2B3a%2FwzsHhSanZs0zIlpbABsgmhYrECeReWN5JCqKI0XY6Aa%2BeVfin6XW5orQyTkKh9Ovh22IV%2BvxNS2gcSdE%2FMCHPCZ2ayltvlONaQsrk2WN0bL3R%2Fz7SVw0AsTzL2wJLY8gYoEQhJQZ4gjBVsx%2F%2BLwkm6NXeFX7UEJLyLpZgltGi2XA86%2BldJpITSamw3XdaKsRTr73CWsQSybDziTE%2Fb2IuTzk0uhEpUkQDtf2wem42MRKL0FMG0wnTVCDtEl1ZWrgzotqSylITrUnZ7QpWtgcAdsg7KFkJL5PpqZfI13BZkdKugBttqtigukaAls8OQhEzhOKbsUDy4HVx%2FG4xHyE1PNP7lnIOr5Q6pZKwkSbII5DjEjaLk%2FSsxLwM5ZyGgVfSAGGrwsfWt8WKPlrjb2K7uHKRiyMUDzuIEISVSFCOmxiHSvQRKRTxn1ogh43nDiZri59yphtTjwHIjbzoVG2MaAzGF3PF22aHkepPBOp6pL%2Bp84JwZbNLMBSYPmRwUV2PXNI0Fw9T7srb35ml7PKBUYvWDvl%2Bevi%2BvnD01h0WsjpU%2FdjGOkgDqOKqfTH8hU6%2BFiVORKcIPJOLjOOfQTPV%2FpQW%2Fu29a8I6RFjQJrrkJKN5kTFVINRGxSAi%2FqNFhTuugh7Sb%2FoElU7cG1uWfunzq65qOddWkK3XbL1Dq3lzhyEwJHYVK7xeho7TifW3edt%2FjbMRMhrAjEyoiY1DbLjntIErgRLF504DnDUi%2Flaed09OkFSVcgarpfEyN7CHfAIWXU8ESlZvmDy3%2FfGWph%2BgvkAis74gpozSPMCcB8GGVwkeCC5nr9aL8b9teMFdqY0l9kV2N04Z1uHHXnNinPb9n3gT2DoIZ7lo7oh7La3YQUZTpjLEWs8qGA8N41g7jO48hhrDn9xvk5%2F5dQJ81hE6P2sQLbCTffq%2FjOG%2FxneM7Xrg%2BTse7zx6v5nFjhgH7Zw8cKcmyBS7R93YE83p73MzdR45g%2FaefwLBaP9UWrFQ%2FeHsXfwA%3D)

**Comment by jaagupku** [comment]
äriklientide hoiustamine failidena, mitte andmebaasis
